version: "3"

services:
  postgres_db:
    image: postgres:14.8-alpine
    restart: always
    volumes:
      - bot_db:/var/lib/postgresql
    ports:
      - "5432:5432"
    env_file:
      - .env

  migration:
    image: migrate/migrate
    restart: on-failure
    command: --path=/migrations/ --database="${DB_CONNECTION}" up
    volumes:
      - ./migrations:/migrations
    env_file:
      - .env
    depends_on:
      - postgres_db

  bot:
    restart: always
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - postgres_db
      - migration

volumes:
  bot_db:
    external: true
