news_resource_url: "https://gnews.io/api/v4/top-headlines"

db:
  host: "localhost"
  port: "5437"
  username: "postgres"
  dbname: "postgres"
  sslmode: "disable"

messages:
  start: "👋Вас приветсвует бот для рассылки новостей\n\n📰Для получения новостной рассылки вам необходимо выбрать интересующие вас новостные категории\n\n✅Для выбора новостных категорий вызовите команду:\n\n%s"
  edit_category: "Выберите интересующие вас категории"
  unknown_command: "Я не знаю такой команды 😢"

errors:
  default: "Произошла неизвестная ошибка."
  invalid_url:  "Это невалидная ссылка."
  unable_to_save: "Не удалось сохранить ссылку в Pocket. Попробуйте пожалуйста позже."