news:
  url: "https://gnews.io/api/v4/top-headlines?lang=ru&category=%s&from=%s&apikey=%s"
  defaultTimeout: 5

rkn:
  url: "https://reestr.rublacklist.net/api/v3/domains/"
  defaultTimeout: 10

cleaner:
  period: 7

messageSender:
  categorySleep: 30
  requestLimit: 96
  mailingTimeEnd: 0
  mailingTimeStart: 7

import:
  batchSize: 1000
  startHour: 2
  delayTime: 1

messages:
  rateLimit: 20
  rateLimitInterval: 10
  startCommand: "👋Вас приветсвует бот для рассылки новостей\n\n📰Для получения новостной рассылки вам необходимо выбрать интересующие вас новостные категории\n\n✅Для выбора новостных категорий вызовите команду:\n\n%s"
  editCategoryCommand: "Нажмите на категорию, чтобы выбрать ее✅"
  unknownCommand: "Я не знаю такой команды 😢"
  manyRequestsCommand: "Слишком много запросов. Пожалуйста, подождите🙏"

errors:
  default: "Произошла неизвестная ошибка."